name: Rust project build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: compiled-binary
          path: target/release/actix-jsonplaceholder
          retention-days: 5
